name: Build Mod
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - run: ./gradlew build
      - uses: actions/upload-artifact@v4  # ← Вот здесь меняем v3 на v4!
        with:
          name: Mod JAR
          path: build/libs/*.jar
